### ISSUE TITLE
Contao Check for Contao 4?

### ISSUE THREAD

**Issue by frontendschlampe** [contao/check#135]
Will Contao Check be dropped in future or will there be a version for Contao 4?

**Comment by fritzmg** [comment]
If you mean the validation: I doubt there will be feasible way of doing that. Otherwise the Contao Check already includes server environment checks for Contao 4.

**Comment by frontendschlampe** [comment]
I mean in general ... ;-)

**Comment by xchs** [comment]
@fritzmg Would it make sense to check the (new) system requirements for Contao 4.5 as well?

**Comment by fritzmg** [comment]
@xchs yes, I will update the Check accordingly, once Contao 4.5 has been released. May be I'll do different checks for Contao 4.4 and 4.5 (rather than just checking for 4.5) since the requirements are so radically different.

**Comment by fritzmg** [comment]
@leofeyer what do you think? Should we include separate checks for Contao 4.4 and 4.5?

**Comment by fritzmg** [comment]
Related: #83

**Comment by leofeyer** [comment]
Using the Contao Check for Contao 4 is a bit weird, because the Contao Check also checks the Live Update and ER2 requirements and it validates existing Contao 3 installations. Nothing of this is useful for Contao 4, therefore I consider the Contao Check part of the Contao 3 ecosystem.

Maybe we should allow to download the Contao Manager through the Contao Check? If we want to keep checking the PHP version for Contao 4, we should include separate checks for Contao 4.4 and 4.5.

**Comment by fritzmg** [comment]
I agree that it is a bit weird. However, since the ER, package manager and Live Update for Contao 3 are separate components, it wouldn't hurt to use the Contao Check for server environment checks for Contao 4 as well imho.

> If we want to keep checking the PHP version for Contao 4, we should include separate checks for Contao 4.4 and 4.5.

Ok, I'll prepare a PR for that when I have the time.

**Comment by fritzmg** [comment]
See https://github.com/contao/check/pull/139
